//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maktab.Sample.Blog.Presentation.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PresentationResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PresentationResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Maktab.Sample.Blog.Presentation.Resources.PresentationResources", typeof(PresentationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string FirstNameProp {
            get {
                return ResourceManager.GetString("FirstNameProp", resourceCulture);
            }
        }
        
        public static string MinLengthStringValidationMessage {
            get {
                return ResourceManager.GetString("MinLengthStringValidationMessage", resourceCulture);
            }
        }
        
        public static string RequiredValidationMessage {
            get {
                return ResourceManager.GetString("RequiredValidationMessage", resourceCulture);
            }
        }
        
        public static string MaxLengthStringValidationMessage {
            get {
                return ResourceManager.GetString("MaxLengthStringValidationMessage", resourceCulture);
            }
        }
        
        public static string LastNameProp {
            get {
                return ResourceManager.GetString("LastNameProp", resourceCulture);
            }
        }
        
        public static string EmailProp {
            get {
                return ResourceManager.GetString("EmailProp", resourceCulture);
            }
        }
        
        public static string InvalidEmailAddress {
            get {
                return ResourceManager.GetString("InvalidEmailAddress", resourceCulture);
            }
        }
        
        public static string UsernameProp {
            get {
                return ResourceManager.GetString("UsernameProp", resourceCulture);
            }
        }
        
        public static string PasswordProp {
            get {
                return ResourceManager.GetString("PasswordProp", resourceCulture);
            }
        }
        
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        public static string RePasswordProp {
            get {
                return ResourceManager.GetString("RePasswordProp", resourceCulture);
            }
        }
        
        public static string InvalidRePassword {
            get {
                return ResourceManager.GetString("InvalidRePassword", resourceCulture);
            }
        }
        
        public static string PhoneNumberProp {
            get {
                return ResourceManager.GetString("PhoneNumberProp", resourceCulture);
            }
        }
        
        public static string InvalidPhoneNumber {
            get {
                return ResourceManager.GetString("InvalidPhoneNumber", resourceCulture);
            }
        }
        
        public static string StringLengthValidationMessage {
            get {
                return ResourceManager.GetString("StringLengthValidationMessage", resourceCulture);
            }
        }
        
        public static string PostTitleProp {
            get {
                return ResourceManager.GetString("PostTitleProp", resourceCulture);
            }
        }
        
        public static string PostTextProp {
            get {
                return ResourceManager.GetString("PostTextProp", resourceCulture);
            }
        }
    }
}
