//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maktab.Sample.Blog.Presentation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PresentationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PresentationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Maktab.Sample.Blog.Presentation.Resources.PresentationResources", typeof(PresentationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment.
        /// </summary>
        public static string AppointmentProp {
            get {
                return ResourceManager.GetString("AppointmentProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department name.
        /// </summary>
        public static string DepartmentNameProp {
            get {
                return ResourceManager.GetString("DepartmentNameProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Service.
        /// </summary>
        public static string DepartmentServiceProp {
            get {
                return ResourceManager.GetString("DepartmentServiceProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor Service.
        /// </summary>
        public static string DoctorServiceProp {
            get {
                return ResourceManager.GetString("DoctorServiceProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string EmailProp {
            get {
                return ResourceManager.GetString("EmailProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string FirstNameProp {
            get {
                return ResourceManager.GetString("FirstNameProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infirmary name.
        /// </summary>
        public static string InfirmaryName {
            get {
                return ResourceManager.GetString("InfirmaryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance Description.
        /// </summary>
        public static string InsuranceDescriptionProp {
            get {
                return ResourceManager.GetString("InsuranceDescriptionProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance Name.
        /// </summary>
        public static string InsuranceNameProp {
            get {
                return ResourceManager.GetString("InsuranceNameProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered email address is not valid..
        /// </summary>
        public static string InvalidEmailAddress {
            get {
                return ResourceManager.GetString("InvalidEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password should contain at least one letter, one digit with minimum length of 8..
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered phone number is invalid..
        /// </summary>
        public static string InvalidPhoneNumber {
            get {
                return ResourceManager.GetString("InvalidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation doesn&apos;t match base password..
        /// </summary>
        public static string InvalidRePassword {
            get {
                return ResourceManager.GetString("InvalidRePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Around The Clock.
        /// </summary>
        public static string IsAroundTheClock {
            get {
                return ResourceManager.GetString("IsAroundTheClock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string LastNameProp {
            get {
                return ResourceManager.GetString("LastNameProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level Of Speciality.
        /// </summary>
        public static string LevelOfSpecialityProp {
            get {
                return ResourceManager.GetString("LevelOfSpecialityProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum length of {0} is {1}..
        /// </summary>
        public static string MaxLengthStringValidationMessage {
            get {
                return ResourceManager.GetString("MaxLengthStringValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical System Code.
        /// </summary>
        public static string MedicalSystemCodeProp {
            get {
                return ResourceManager.GetString("MedicalSystemCodeProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical System Code Should Consist of Only Numbers.
        /// </summary>
        public static string MedicalSystemStringValidationMessage {
            get {
                return ResourceManager.GetString("MedicalSystemStringValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Length of {0} is {1}..
        /// </summary>
        public static string MinLengthStringValidationMessage {
            get {
                return ResourceManager.GetString("MinLengthStringValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National Code.
        /// </summary>
        public static string NationalCodeProp {
            get {
                return ResourceManager.GetString("NationalCodeProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National Code Should Consist of Only Numbers.
        /// </summary>
        public static string NationalCodeStringValidationMessage {
            get {
                return ResourceManager.GetString("NationalCodeStringValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordProp {
            get {
                return ResourceManager.GetString("PasswordProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Description.
        /// </summary>
        public static string PatientDescriptionProp {
            get {
                return ResourceManager.GetString("PatientDescriptionProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string PhoneNumberProp {
            get {
                return ResourceManager.GetString("PhoneNumberProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post text.
        /// </summary>
        public static string PostTextProp {
            get {
                return ResourceManager.GetString("PostTextProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post title.
        /// </summary>
        public static string PostTitleProp {
            get {
                return ResourceManager.GetString("PostTitleProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prescription Description.
        /// </summary>
        public static string PrescriptionDescriptionProp {
            get {
                return ResourceManager.GetString("PrescriptionDescriptionProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password confirmation.
        /// </summary>
        public static string RePasswordProp {
            get {
                return ResourceManager.GetString("RePasswordProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required..
        /// </summary>
        public static string RequiredValidationMessage {
            get {
                return ResourceManager.GetString("RequiredValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s length should be between {1}, {2}..
        /// </summary>
        public static string StringLengthValidationMessage {
            get {
                return ResourceManager.GetString("StringLengthValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported Incurance.
        /// </summary>
        public static string SupportedInsurance {
            get {
                return ResourceManager.GetString("SupportedInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string UsernameProp {
            get {
                return ResourceManager.GetString("UsernameProp", resourceCulture);
            }
        }
    }
}
